name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest # Firefox in it
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: sudo apt-get install xvfb
      - run: npm install
      - run: DEBUG=eslint:cli-engine npm run lint:all
      - run: npm run build
      - run: xvfb-run --auto-servernum -- npm test
        env:
          CHROME_BIN: chromium-browser
      - run: cat */coverage/lcov.info
      - name: Coveralls SDK
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./sdk/coverage/lcov.info
          parallel: true
      - name: Coveralls Subscriptions
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./subscriptions/coverage/lcov.info
          parallel: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  canary-release:
    needs: test
    if: ${{ github.event_name == 'push' && github.repository_owner == 'ringcentral' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: npm install
      - run: npm run build
      - run: npm run publish:release -- --canary --preid=$BRANCH.$GITHUB_RUN_ID.$GITHUB_RUN_NUMBER --dist-tag=$BRANCH --yes
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
