name: Release

on:
  push:
    tags:
      - "**.**.**"

jobs:
  release:
    if: ${{ github.repository_owner == 'ringcentral' }}
    runs-on: ubuntu-latest # Firefox in it
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - name: Get the version
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - run: npm install
      - run: npm run build
      - run: npm run publish:release -- $SOURCE_TAG --yes
        env:
          SOURCE_TAG: ${{ steps.get_version.outputs.SOURCE_TAG }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sdk/dist/ringcentral.js
            sdk/dist/ringcentral.js.map
            sdk/dist/ringcentral.min.js
            sdk/dist/ringcentral.min.js.map
            subscriptions/dist/ringcentral-subscriptions.js
            subscriptions/dist/ringcentral-subscriptions.js.map
            subscriptions/dist/ringcentral-subscriptions.min.js
            subscriptions/dist/ringcentral-subscriptions.min.js.map
        env:
          GITHUB_REPOSITORY: ringcentral/ringcentral-js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
